config: 
  name: +
block: [block1, block2]
day: 1
dayblock: [day1_block1, day1_block2]
pos: [2,4,5,6,8]
class: [1,2,3,4,5,6]
grasp_dec:
  '1': power
  '2': lateral
  '3': tripod
  '4': pointer
  '5': open
  '6': rest