config: 
  name: x
block: [block1, block2]
day: 2
dayblock: [day2_block1, day2_block2]
pos: [1,3,5,7,9]
class: [1,2,3,4,5,6]
grasp_dec:
  '1': power
  '2': lateral
  '3': tripod
  '4': pointer
  '5': open
  '6': rest