General:
  root_path: ""
  participant : 1
  grasps : ['rest', 'tripod', 'lateral', 'pointer', 'power']
  trials : 5
  block_configuration : ['2', '4', '5', '6', '8'] # '+'
  # block_configuration : ['1', '3', '5', '7', '9'] # 'x'
  classes : [1,2,3,4,5,6]
  block : 1